package com.restaurace;

public enum Menu{
    BEER_LARGE_10,
    BEER_SMALL_10,
    BOLONSKE_SPAGETTI,
    HRANOLKY,
    KOFOLA_LARGE,
    KOFOLA_SMALL,
    KURECI_RIZEK,
    PIZZA_GRANDE,
    PIZZA_PEPPERONI,
    PIZZA_VEGAN,
    POLEVKA,
    PSTRUH_NA_VINE;
}
